'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.276
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicoJogo
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://projeto_2/", ConfigurationName:="ServicoJogo.JogoTradutorItaliano")>  _
    Public Interface JogoTradutorItaliano
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getPlacarIndividualRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getPlacarIndividualResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPlacarIndividual(ByVal request As ServicoJogo.getPlacarIndividualRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getPlacarIndividualResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setNewDesafioItalianoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setNewDesafioItalianoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setNewDesafioItaliano(ByVal request As ServicoJogo.setNewDesafioItalianoRequest) As ServicoJogo.setNewDesafioItalianoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/resetAdminRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/resetAdminResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub resetAdmin()
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getPlacarGeralRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getPlacarGeralResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPlacarGeral(ByVal request As ServicoJogo.getPlacarGeralRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getPlacarGeralResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getRegrasRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getRegrasResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getRegras(ByVal request As ServicoJogo.getRegrasRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getRegrasResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/lancarDesafioRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/lancarDesafioResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function lancarDesafio(ByVal request As ServicoJogo.lancarDesafioRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.lancarDesafioResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getQtdJogadoresRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getQtdJogadoresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getQtdJogadores(ByVal request As ServicoJogo.getQtdJogadoresRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getQtdJogadoresResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/adminJogoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/adminJogoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function adminJogo(ByVal request As ServicoJogo.adminJogoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.adminJogoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/monitorAdminRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/monitorAdminResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub monitorAdmin()
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/registrarRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/registrarResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registrar(ByVal request As ServicoJogo.registrarRequest) As ServicoJogo.registrarResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/removerJogadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/removerJogadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function removerJogador(ByVal request As ServicoJogo.removerJogadorRequest) As ServicoJogo.removerJogadorResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/checarRespostaRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/checarRespostaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function checarResposta(ByVal request As ServicoJogo.checarRespostaRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.checarRespostaResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/jogadorEliminadoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/jogadorEliminadoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function jogadorEliminado(ByVal request As ServicoJogo.jogadorEliminadoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.jogadorEliminadoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setIdJogadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setIdJogadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setIdJogador(ByVal request As ServicoJogo.setIdJogadorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.setIdJogadorResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/gameOverRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/gameOverResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function gameOver(ByVal request As ServicoJogo.gameOverRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.gameOverResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/ultimoIdRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/ultimoIdResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ultimoId(ByVal request As ServicoJogo.ultimoIdRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.ultimoIdResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getStatusRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatus(ByVal request As ServicoJogo.getStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getStatusResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setStatusRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setStatus(ByVal request As ServicoJogo.setStatusRequest) As ServicoJogo.setStatusResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getDesafioItalianoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getDesafioItalianoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDesafioItaliano(ByVal request As ServicoJogo.getDesafioItalianoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getDesafioItalianoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getJogadorVencedorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getJogadorVencedorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getJogadorVencedor(ByVal request As ServicoJogo.getJogadorVencedorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getJogadorVencedorResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/listarJogadoresRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/listarJogadoresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarJogadores(ByVal request As ServicoJogo.listarJogadoresRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.listarJogadoresResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/desistirJogoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/desistirJogoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function desistirJogo(ByVal request As ServicoJogo.desistirJogoRequest) As ServicoJogo.desistirJogoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getIdGanhadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getIdGanhadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getIdGanhador(ByVal request As ServicoJogo.getIdGanhadorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServicoJogo.getIdGanhadorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/resetGameRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/resetGameResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub resetGame()
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarIndividual", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarIndividualRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarIndividualResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarIndividualResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setNewDesafioItaliano", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setNewDesafioItalianoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setNewDesafioItalianoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setNewDesafioItalianoResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarGeral", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarGeralRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarGeralResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarGeralResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRegras", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getRegrasRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRegrasResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getRegrasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="lancarDesafio", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class lancarDesafioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="lancarDesafioResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class lancarDesafioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getQtdJogadores", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getQtdJogadoresRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getQtdJogadoresResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getQtdJogadoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="adminJogo", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class adminJogoRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="adminJogoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class adminJogoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://projeto_2/")>  _
    Partial Public Class jogadorTradutor
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idJogadorField As Integer
        
        Private nomeField As String
        
        Private pontuacaoField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property idJogador() As Integer
            Get
                Return Me.idJogadorField
            End Get
            Set
                Me.idJogadorField = value
                Me.RaisePropertyChanged("idJogador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
                Me.RaisePropertyChanged("nome")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property pontuacao() As Integer
            Get
                Return Me.pontuacaoField
            End Get
            Set
                Me.pontuacaoField = value
                Me.RaisePropertyChanged("pontuacao")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="registrar", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class registrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As ServicoJogo.jogadorTradutor
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As ServicoJogo.jogadorTradutor)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="registrarResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class registrarResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="removerJogador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class removerJogadorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="removerJogadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class removerJogadorResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="checarResposta", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class checarRespostaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg1 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As String, ByVal arg1 As Integer)
            MyBase.New
            Me.arg0 = arg0
            Me.arg1 = arg1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="checarRespostaResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class checarRespostaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="jogadorEliminado", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class jogadorEliminadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="jogadorEliminadoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class jogadorEliminadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Boolean)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setIdJogador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setIdJogadorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setIdJogadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setIdJogadorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="gameOver", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class gameOverRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="gameOverResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class gameOverResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Boolean)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ultimoId", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class ultimoIdRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ultimoIdResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class ultimoIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatus", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getStatusRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setStatus", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setStatusResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setStatusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDesafioItaliano", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getDesafioItalianoRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDesafioItalianoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getDesafioItalianoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getJogadorVencedor", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getJogadorVencedorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getJogadorVencedorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getJogadorVencedorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listarJogadores", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class listarJogadoresRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listarJogadoresResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class listarJogadoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="desistirJogo", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class desistirJogoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="desistirJogoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class desistirJogoResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getIdGanhador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getIdGanhadorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getIdGanhadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getIdGanhadorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface JogoTradutorItalianoChannel
        Inherits ServicoJogo.JogoTradutorItaliano, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class JogoTradutorItalianoClient
        Inherits System.ServiceModel.ClientBase(Of ServicoJogo.JogoTradutorItaliano)
        Implements ServicoJogo.JogoTradutorItaliano
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getPlacarIndividual(ByVal request As ServicoJogo.getPlacarIndividualRequest) As ServicoJogo.getPlacarIndividualResponse Implements ServicoJogo.JogoTradutorItaliano.getPlacarIndividual
            Return MyBase.Channel.getPlacarIndividual(request)
        End Function
        
        Public Function getPlacarIndividual(ByVal arg0 As Integer) As String
            Dim inValue As ServicoJogo.getPlacarIndividualRequest = New ServicoJogo.getPlacarIndividualRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.getPlacarIndividualResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getPlacarIndividual(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_setNewDesafioItaliano(ByVal request As ServicoJogo.setNewDesafioItalianoRequest) As ServicoJogo.setNewDesafioItalianoResponse Implements ServicoJogo.JogoTradutorItaliano.setNewDesafioItaliano
            Return MyBase.Channel.setNewDesafioItaliano(request)
        End Function
        
        Public Sub setNewDesafioItaliano(ByVal arg0 As Integer)
            Dim inValue As ServicoJogo.setNewDesafioItalianoRequest = New ServicoJogo.setNewDesafioItalianoRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.setNewDesafioItalianoResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).setNewDesafioItaliano(inValue)
        End Sub
        
        Public Sub resetAdmin() Implements ServicoJogo.JogoTradutorItaliano.resetAdmin
            MyBase.Channel.resetAdmin
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getPlacarGeral(ByVal request As ServicoJogo.getPlacarGeralRequest) As ServicoJogo.getPlacarGeralResponse Implements ServicoJogo.JogoTradutorItaliano.getPlacarGeral
            Return MyBase.Channel.getPlacarGeral(request)
        End Function
        
        Public Function getPlacarGeral() As String
            Dim inValue As ServicoJogo.getPlacarGeralRequest = New ServicoJogo.getPlacarGeralRequest()
            Dim retVal As ServicoJogo.getPlacarGeralResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getPlacarGeral(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getRegras(ByVal request As ServicoJogo.getRegrasRequest) As ServicoJogo.getRegrasResponse Implements ServicoJogo.JogoTradutorItaliano.getRegras
            Return MyBase.Channel.getRegras(request)
        End Function
        
        Public Function getRegras() As String
            Dim inValue As ServicoJogo.getRegrasRequest = New ServicoJogo.getRegrasRequest()
            Dim retVal As ServicoJogo.getRegrasResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getRegras(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_lancarDesafio(ByVal request As ServicoJogo.lancarDesafioRequest) As ServicoJogo.lancarDesafioResponse Implements ServicoJogo.JogoTradutorItaliano.lancarDesafio
            Return MyBase.Channel.lancarDesafio(request)
        End Function
        
        Public Function lancarDesafio(ByVal arg0 As Integer) As String
            Dim inValue As ServicoJogo.lancarDesafioRequest = New ServicoJogo.lancarDesafioRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.lancarDesafioResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).lancarDesafio(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getQtdJogadores(ByVal request As ServicoJogo.getQtdJogadoresRequest) As ServicoJogo.getQtdJogadoresResponse Implements ServicoJogo.JogoTradutorItaliano.getQtdJogadores
            Return MyBase.Channel.getQtdJogadores(request)
        End Function
        
        Public Function getQtdJogadores() As Integer
            Dim inValue As ServicoJogo.getQtdJogadoresRequest = New ServicoJogo.getQtdJogadoresRequest()
            Dim retVal As ServicoJogo.getQtdJogadoresResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getQtdJogadores(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_adminJogo(ByVal request As ServicoJogo.adminJogoRequest) As ServicoJogo.adminJogoResponse Implements ServicoJogo.JogoTradutorItaliano.adminJogo
            Return MyBase.Channel.adminJogo(request)
        End Function
        
        Public Function adminJogo() As Integer
            Dim inValue As ServicoJogo.adminJogoRequest = New ServicoJogo.adminJogoRequest()
            Dim retVal As ServicoJogo.adminJogoResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).adminJogo(inValue)
            Return retVal.[return]
        End Function
        
        Public Sub monitorAdmin() Implements ServicoJogo.JogoTradutorItaliano.monitorAdmin
            MyBase.Channel.monitorAdmin
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_registrar(ByVal request As ServicoJogo.registrarRequest) As ServicoJogo.registrarResponse Implements ServicoJogo.JogoTradutorItaliano.registrar
            Return MyBase.Channel.registrar(request)
        End Function
        
        Public Sub registrar(ByVal arg0 As ServicoJogo.jogadorTradutor)
            Dim inValue As ServicoJogo.registrarRequest = New ServicoJogo.registrarRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.registrarResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).registrar(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_removerJogador(ByVal request As ServicoJogo.removerJogadorRequest) As ServicoJogo.removerJogadorResponse Implements ServicoJogo.JogoTradutorItaliano.removerJogador
            Return MyBase.Channel.removerJogador(request)
        End Function
        
        Public Sub removerJogador(ByVal arg0 As Integer)
            Dim inValue As ServicoJogo.removerJogadorRequest = New ServicoJogo.removerJogadorRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.removerJogadorResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).removerJogador(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_checarResposta(ByVal request As ServicoJogo.checarRespostaRequest) As ServicoJogo.checarRespostaResponse Implements ServicoJogo.JogoTradutorItaliano.checarResposta
            Return MyBase.Channel.checarResposta(request)
        End Function
        
        Public Function checarResposta(ByVal arg0 As String, ByVal arg1 As Integer) As Integer
            Dim inValue As ServicoJogo.checarRespostaRequest = New ServicoJogo.checarRespostaRequest()
            inValue.arg0 = arg0
            inValue.arg1 = arg1
            Dim retVal As ServicoJogo.checarRespostaResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).checarResposta(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_jogadorEliminado(ByVal request As ServicoJogo.jogadorEliminadoRequest) As ServicoJogo.jogadorEliminadoResponse Implements ServicoJogo.JogoTradutorItaliano.jogadorEliminado
            Return MyBase.Channel.jogadorEliminado(request)
        End Function
        
        Public Function jogadorEliminado(ByVal arg0 As Integer) As Boolean
            Dim inValue As ServicoJogo.jogadorEliminadoRequest = New ServicoJogo.jogadorEliminadoRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.jogadorEliminadoResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).jogadorEliminado(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_setIdJogador(ByVal request As ServicoJogo.setIdJogadorRequest) As ServicoJogo.setIdJogadorResponse Implements ServicoJogo.JogoTradutorItaliano.setIdJogador
            Return MyBase.Channel.setIdJogador(request)
        End Function
        
        Public Function setIdJogador() As Integer
            Dim inValue As ServicoJogo.setIdJogadorRequest = New ServicoJogo.setIdJogadorRequest()
            Dim retVal As ServicoJogo.setIdJogadorResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).setIdJogador(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_gameOver(ByVal request As ServicoJogo.gameOverRequest) As ServicoJogo.gameOverResponse Implements ServicoJogo.JogoTradutorItaliano.gameOver
            Return MyBase.Channel.gameOver(request)
        End Function
        
        Public Function gameOver() As Boolean
            Dim inValue As ServicoJogo.gameOverRequest = New ServicoJogo.gameOverRequest()
            Dim retVal As ServicoJogo.gameOverResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).gameOver(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_ultimoId(ByVal request As ServicoJogo.ultimoIdRequest) As ServicoJogo.ultimoIdResponse Implements ServicoJogo.JogoTradutorItaliano.ultimoId
            Return MyBase.Channel.ultimoId(request)
        End Function
        
        Public Function ultimoId() As Integer
            Dim inValue As ServicoJogo.ultimoIdRequest = New ServicoJogo.ultimoIdRequest()
            Dim retVal As ServicoJogo.ultimoIdResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).ultimoId(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getStatus(ByVal request As ServicoJogo.getStatusRequest) As ServicoJogo.getStatusResponse Implements ServicoJogo.JogoTradutorItaliano.getStatus
            Return MyBase.Channel.getStatus(request)
        End Function
        
        Public Function getStatus() As Integer
            Dim inValue As ServicoJogo.getStatusRequest = New ServicoJogo.getStatusRequest()
            Dim retVal As ServicoJogo.getStatusResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getStatus(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_setStatus(ByVal request As ServicoJogo.setStatusRequest) As ServicoJogo.setStatusResponse Implements ServicoJogo.JogoTradutorItaliano.setStatus
            Return MyBase.Channel.setStatus(request)
        End Function
        
        Public Sub setStatus(ByVal arg0 As Integer)
            Dim inValue As ServicoJogo.setStatusRequest = New ServicoJogo.setStatusRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.setStatusResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).setStatus(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getDesafioItaliano(ByVal request As ServicoJogo.getDesafioItalianoRequest) As ServicoJogo.getDesafioItalianoResponse Implements ServicoJogo.JogoTradutorItaliano.getDesafioItaliano
            Return MyBase.Channel.getDesafioItaliano(request)
        End Function
        
        Public Function getDesafioItaliano() As String
            Dim inValue As ServicoJogo.getDesafioItalianoRequest = New ServicoJogo.getDesafioItalianoRequest()
            Dim retVal As ServicoJogo.getDesafioItalianoResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getDesafioItaliano(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getJogadorVencedor(ByVal request As ServicoJogo.getJogadorVencedorRequest) As ServicoJogo.getJogadorVencedorResponse Implements ServicoJogo.JogoTradutorItaliano.getJogadorVencedor
            Return MyBase.Channel.getJogadorVencedor(request)
        End Function
        
        Public Function getJogadorVencedor() As String
            Dim inValue As ServicoJogo.getJogadorVencedorRequest = New ServicoJogo.getJogadorVencedorRequest()
            Dim retVal As ServicoJogo.getJogadorVencedorResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getJogadorVencedor(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_listarJogadores(ByVal request As ServicoJogo.listarJogadoresRequest) As ServicoJogo.listarJogadoresResponse Implements ServicoJogo.JogoTradutorItaliano.listarJogadores
            Return MyBase.Channel.listarJogadores(request)
        End Function
        
        Public Function listarJogadores() As String
            Dim inValue As ServicoJogo.listarJogadoresRequest = New ServicoJogo.listarJogadoresRequest()
            Dim retVal As ServicoJogo.listarJogadoresResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).listarJogadores(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_desistirJogo(ByVal request As ServicoJogo.desistirJogoRequest) As ServicoJogo.desistirJogoResponse Implements ServicoJogo.JogoTradutorItaliano.desistirJogo
            Return MyBase.Channel.desistirJogo(request)
        End Function
        
        Public Sub desistirJogo(ByVal arg0 As Integer)
            Dim inValue As ServicoJogo.desistirJogoRequest = New ServicoJogo.desistirJogoRequest()
            inValue.arg0 = arg0
            Dim retVal As ServicoJogo.desistirJogoResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).desistirJogo(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoJogo_JogoTradutorItaliano_getIdGanhador(ByVal request As ServicoJogo.getIdGanhadorRequest) As ServicoJogo.getIdGanhadorResponse Implements ServicoJogo.JogoTradutorItaliano.getIdGanhador
            Return MyBase.Channel.getIdGanhador(request)
        End Function
        
        Public Function getIdGanhador() As Integer
            Dim inValue As ServicoJogo.getIdGanhadorRequest = New ServicoJogo.getIdGanhadorRequest()
            Dim retVal As ServicoJogo.getIdGanhadorResponse = CType(Me,ServicoJogo.JogoTradutorItaliano).getIdGanhador(inValue)
            Return retVal.[return]
        End Function
        
        Public Sub resetGame() Implements ServicoJogo.JogoTradutorItaliano.resetGame
            MyBase.Channel.resetGame
        End Sub
    End Class
End Namespace
