'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.276
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Jogo
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://projeto_2/", ConfigurationName:="Jogo.JogoTradutorItaliano")>  _
    Public Interface JogoTradutorItaliano
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/resetAdminRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/resetAdminResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub resetAdmin()
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/gameOverRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/gameOverResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function gameOver(ByVal request As Jogo.gameOverRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.gameOverResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/ultimoIdRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/ultimoIdResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ultimoId(ByVal request As Jogo.ultimoIdRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.ultimoIdResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getPlacarGeralRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getPlacarGeralResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPlacarGeral(ByVal request As Jogo.getPlacarGeralRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getPlacarGeralResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getRegrasRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getRegrasResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getRegras(ByVal request As Jogo.getRegrasRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getRegrasResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/lancarDesafioRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/lancarDesafioResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function lancarDesafio(ByVal request As Jogo.lancarDesafioRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.lancarDesafioResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getQtdJogadoresRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getQtdJogadoresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getQtdJogadores(ByVal request As Jogo.getQtdJogadoresRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getQtdJogadoresResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/adminJogoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/adminJogoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function adminJogo(ByVal request As Jogo.adminJogoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.adminJogoResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/registrarRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/registrarResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registrar(ByVal request As Jogo.registrarRequest) As Jogo.registrarResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getStatusRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatus(ByVal request As Jogo.getStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getStatusResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setStatusRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setStatus(ByVal request As Jogo.setStatusRequest) As Jogo.setStatusResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/removerJogadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/removerJogadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function removerJogador(ByVal request As Jogo.removerJogadorRequest) As Jogo.removerJogadorResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/checarRespostaRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/checarRespostaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function checarResposta(ByVal request As Jogo.checarRespostaRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.checarRespostaResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/jogadorEliminadoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/jogadorEliminadoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function jogadorEliminado(ByVal request As Jogo.jogadorEliminadoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.jogadorEliminadoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setIdJogadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setIdJogadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setIdJogador(ByVal request As Jogo.setIdJogadorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.setIdJogadorResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/listarJogadoresRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/listarJogadoresResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarJogadores(ByVal request As Jogo.listarJogadoresRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.listarJogadoresResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/desistirJogoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/desistirJogoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function desistirJogo(ByVal request As Jogo.desistirJogoRequest) As Jogo.desistirJogoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getIdGanhadorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getIdGanhadorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getIdGanhador(ByVal request As Jogo.getIdGanhadorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getIdGanhadorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/resetGameRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/resetGameResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub resetGame()
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getPlacarIndividualRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getPlacarIndividualResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPlacarIndividual(ByVal request As Jogo.getPlacarIndividualRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getPlacarIndividualResponse
        
        'CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/setNewDesafioItalianoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/setNewDesafioItalianoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setNewDesafioItaliano(ByVal request As Jogo.setNewDesafioItalianoRequest) As Jogo.setNewDesafioItalianoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getDesafioItalianoRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getDesafioItalianoResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDesafioItaliano(ByVal request As Jogo.getDesafioItalianoRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getDesafioItalianoResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://projeto_2/JogoTradutorItaliano/getJogadorVendedorRequest", ReplyAction:="http://projeto_2/JogoTradutorItaliano/getJogadorVendedorResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getJogadorVendedor(ByVal request As Jogo.getJogadorVendedorRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Jogo.getJogadorVendedorResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="gameOver", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class gameOverRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="gameOverResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class gameOverResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Boolean)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ultimoId", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class ultimoIdRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ultimoIdResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class ultimoIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarGeral", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarGeralRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarGeralResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarGeralResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRegras", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getRegrasRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRegrasResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getRegrasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="lancarDesafio", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class lancarDesafioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="lancarDesafioResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class lancarDesafioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getQtdJogadores", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getQtdJogadoresRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getQtdJogadoresResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getQtdJogadoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="adminJogo", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class adminJogoRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="adminJogoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class adminJogoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://projeto_2/")>  _
    Partial Public Class jogadorTradutor
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idJogadorField As Integer
        
        Private nomeField As String
        
        Private pontuacaoField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property idJogador() As Integer
            Get
                Return Me.idJogadorField
            End Get
            Set
                Me.idJogadorField = value
                Me.RaisePropertyChanged("idJogador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
                Me.RaisePropertyChanged("nome")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property pontuacao() As Integer
            Get
                Return Me.pontuacaoField
            End Get
            Set
                Me.pontuacaoField = value
                Me.RaisePropertyChanged("pontuacao")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="registrar", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class registrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Jogo.jogadorTradutor
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Jogo.jogadorTradutor)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="registrarResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class registrarResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatus", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getStatusRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setStatus", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setStatusResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setStatusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="removerJogador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class removerJogadorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="removerJogadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class removerJogadorResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="checarResposta", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class checarRespostaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg1 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As String, ByVal arg1 As Integer)
            MyBase.New
            Me.arg0 = arg0
            Me.arg1 = arg1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="checarRespostaResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class checarRespostaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="jogadorEliminado", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class jogadorEliminadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="jogadorEliminadoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class jogadorEliminadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Boolean)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setIdJogador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setIdJogadorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setIdJogadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setIdJogadorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listarJogadores", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class listarJogadoresRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="listarJogadoresResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class listarJogadoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="desistirJogo", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class desistirJogoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="desistirJogoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class desistirJogoResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getIdGanhador", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getIdGanhadorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getIdGanhadorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getIdGanhadorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Integer)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarIndividual", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarIndividualRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPlacarIndividualResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getPlacarIndividualResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setNewDesafioItaliano", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setNewDesafioItalianoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public arg0 As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As Integer)
            MyBase.New
            Me.arg0 = arg0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="setNewDesafioItalianoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class setNewDesafioItalianoResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDesafioItaliano", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getDesafioItalianoRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getDesafioItalianoResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getDesafioItalianoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getJogadorVendedor", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getJogadorVendedorRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getJogadorVendedorResponse", WrapperNamespace:="http://projeto_2/", IsWrapped:=true)>  _
    Partial Public Class getJogadorVendedorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://projeto_2/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface JogoTradutorItalianoChannel
        Inherits Jogo.JogoTradutorItaliano, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class JogoTradutorItalianoClient
        Inherits System.ServiceModel.ClientBase(Of Jogo.JogoTradutorItaliano)
        Implements Jogo.JogoTradutorItaliano
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub resetAdmin() Implements Jogo.JogoTradutorItaliano.resetAdmin
            MyBase.Channel.resetAdmin
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_gameOver(ByVal request As Jogo.gameOverRequest) As Jogo.gameOverResponse Implements Jogo.JogoTradutorItaliano.gameOver
            Return MyBase.Channel.gameOver(request)
        End Function
        
        Public Function gameOver() As Boolean
            Dim inValue As Jogo.gameOverRequest = New Jogo.gameOverRequest()
            Dim retVal As Jogo.gameOverResponse = CType(Me,Jogo.JogoTradutorItaliano).gameOver(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_ultimoId(ByVal request As Jogo.ultimoIdRequest) As Jogo.ultimoIdResponse Implements Jogo.JogoTradutorItaliano.ultimoId
            Return MyBase.Channel.ultimoId(request)
        End Function
        
        Public Function ultimoId() As Integer
            Dim inValue As Jogo.ultimoIdRequest = New Jogo.ultimoIdRequest()
            Dim retVal As Jogo.ultimoIdResponse = CType(Me,Jogo.JogoTradutorItaliano).ultimoId(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getPlacarGeral(ByVal request As Jogo.getPlacarGeralRequest) As Jogo.getPlacarGeralResponse Implements Jogo.JogoTradutorItaliano.getPlacarGeral
            Return MyBase.Channel.getPlacarGeral(request)
        End Function
        
        Public Function getPlacarGeral() As String
            Dim inValue As Jogo.getPlacarGeralRequest = New Jogo.getPlacarGeralRequest()
            Dim retVal As Jogo.getPlacarGeralResponse = CType(Me,Jogo.JogoTradutorItaliano).getPlacarGeral(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getRegras(ByVal request As Jogo.getRegrasRequest) As Jogo.getRegrasResponse Implements Jogo.JogoTradutorItaliano.getRegras
            Return MyBase.Channel.getRegras(request)
        End Function
        
        Public Function getRegras() As String
            Dim inValue As Jogo.getRegrasRequest = New Jogo.getRegrasRequest()
            Dim retVal As Jogo.getRegrasResponse = CType(Me,Jogo.JogoTradutorItaliano).getRegras(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_lancarDesafio(ByVal request As Jogo.lancarDesafioRequest) As Jogo.lancarDesafioResponse Implements Jogo.JogoTradutorItaliano.lancarDesafio
            Return MyBase.Channel.lancarDesafio(request)
        End Function
        
        Public Function lancarDesafio(ByVal arg0 As Integer) As String
            Dim inValue As Jogo.lancarDesafioRequest = New Jogo.lancarDesafioRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.lancarDesafioResponse = CType(Me,Jogo.JogoTradutorItaliano).lancarDesafio(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getQtdJogadores(ByVal request As Jogo.getQtdJogadoresRequest) As Jogo.getQtdJogadoresResponse Implements Jogo.JogoTradutorItaliano.getQtdJogadores
            Return MyBase.Channel.getQtdJogadores(request)
        End Function
        
        Public Function getQtdJogadores() As Integer
            Dim inValue As Jogo.getQtdJogadoresRequest = New Jogo.getQtdJogadoresRequest()
            Dim retVal As Jogo.getQtdJogadoresResponse = CType(Me,Jogo.JogoTradutorItaliano).getQtdJogadores(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_adminJogo(ByVal request As Jogo.adminJogoRequest) As Jogo.adminJogoResponse Implements Jogo.JogoTradutorItaliano.adminJogo
            Return MyBase.Channel.adminJogo(request)
        End Function
        
        Public Function adminJogo() As Integer
            Dim inValue As Jogo.adminJogoRequest = New Jogo.adminJogoRequest()
            Dim retVal As Jogo.adminJogoResponse = CType(Me,Jogo.JogoTradutorItaliano).adminJogo(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_registrar(ByVal request As Jogo.registrarRequest) As Jogo.registrarResponse Implements Jogo.JogoTradutorItaliano.registrar
            Return MyBase.Channel.registrar(request)
        End Function
        
        Public Sub registrar(ByVal arg0 As Jogo.jogadorTradutor)
            Dim inValue As Jogo.registrarRequest = New Jogo.registrarRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.registrarResponse = CType(Me,Jogo.JogoTradutorItaliano).registrar(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getStatus(ByVal request As Jogo.getStatusRequest) As Jogo.getStatusResponse Implements Jogo.JogoTradutorItaliano.getStatus
            Return MyBase.Channel.getStatus(request)
        End Function
        
        Public Function getStatus() As Integer
            Dim inValue As Jogo.getStatusRequest = New Jogo.getStatusRequest()
            Dim retVal As Jogo.getStatusResponse = CType(Me,Jogo.JogoTradutorItaliano).getStatus(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_setStatus(ByVal request As Jogo.setStatusRequest) As Jogo.setStatusResponse Implements Jogo.JogoTradutorItaliano.setStatus
            Return MyBase.Channel.setStatus(request)
        End Function
        
        Public Sub setStatus(ByVal arg0 As Integer)
            Dim inValue As Jogo.setStatusRequest = New Jogo.setStatusRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.setStatusResponse = CType(Me,Jogo.JogoTradutorItaliano).setStatus(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_removerJogador(ByVal request As Jogo.removerJogadorRequest) As Jogo.removerJogadorResponse Implements Jogo.JogoTradutorItaliano.removerJogador
            Return MyBase.Channel.removerJogador(request)
        End Function
        
        Public Sub removerJogador(ByVal arg0 As Integer)
            Dim inValue As Jogo.removerJogadorRequest = New Jogo.removerJogadorRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.removerJogadorResponse = CType(Me,Jogo.JogoTradutorItaliano).removerJogador(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_checarResposta(ByVal request As Jogo.checarRespostaRequest) As Jogo.checarRespostaResponse Implements Jogo.JogoTradutorItaliano.checarResposta
            Return MyBase.Channel.checarResposta(request)
        End Function
        
        Public Function checarResposta(ByVal arg0 As String, ByVal arg1 As Integer) As Integer
            Dim inValue As Jogo.checarRespostaRequest = New Jogo.checarRespostaRequest()
            inValue.arg0 = arg0
            inValue.arg1 = arg1
            Dim retVal As Jogo.checarRespostaResponse = CType(Me,Jogo.JogoTradutorItaliano).checarResposta(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_jogadorEliminado(ByVal request As Jogo.jogadorEliminadoRequest) As Jogo.jogadorEliminadoResponse Implements Jogo.JogoTradutorItaliano.jogadorEliminado
            Return MyBase.Channel.jogadorEliminado(request)
        End Function
        
        Public Function jogadorEliminado(ByVal arg0 As Integer) As Boolean
            Dim inValue As Jogo.jogadorEliminadoRequest = New Jogo.jogadorEliminadoRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.jogadorEliminadoResponse = CType(Me,Jogo.JogoTradutorItaliano).jogadorEliminado(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_setIdJogador(ByVal request As Jogo.setIdJogadorRequest) As Jogo.setIdJogadorResponse Implements Jogo.JogoTradutorItaliano.setIdJogador
            Return MyBase.Channel.setIdJogador(request)
        End Function
        
        Public Function setIdJogador() As Integer
            Dim inValue As Jogo.setIdJogadorRequest = New Jogo.setIdJogadorRequest()
            Dim retVal As Jogo.setIdJogadorResponse = CType(Me,Jogo.JogoTradutorItaliano).setIdJogador(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_listarJogadores(ByVal request As Jogo.listarJogadoresRequest) As Jogo.listarJogadoresResponse Implements Jogo.JogoTradutorItaliano.listarJogadores
            Return MyBase.Channel.listarJogadores(request)
        End Function
        
        Public Function listarJogadores() As String
            Dim inValue As Jogo.listarJogadoresRequest = New Jogo.listarJogadoresRequest()
            Dim retVal As Jogo.listarJogadoresResponse = CType(Me,Jogo.JogoTradutorItaliano).listarJogadores(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_desistirJogo(ByVal request As Jogo.desistirJogoRequest) As Jogo.desistirJogoResponse Implements Jogo.JogoTradutorItaliano.desistirJogo
            Return MyBase.Channel.desistirJogo(request)
        End Function
        
        Public Sub desistirJogo(ByVal arg0 As Integer)
            Dim inValue As Jogo.desistirJogoRequest = New Jogo.desistirJogoRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.desistirJogoResponse = CType(Me,Jogo.JogoTradutorItaliano).desistirJogo(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getIdGanhador(ByVal request As Jogo.getIdGanhadorRequest) As Jogo.getIdGanhadorResponse Implements Jogo.JogoTradutorItaliano.getIdGanhador
            Return MyBase.Channel.getIdGanhador(request)
        End Function
        
        Public Function getIdGanhador() As Integer
            Dim inValue As Jogo.getIdGanhadorRequest = New Jogo.getIdGanhadorRequest()
            Dim retVal As Jogo.getIdGanhadorResponse = CType(Me,Jogo.JogoTradutorItaliano).getIdGanhador(inValue)
            Return retVal.[return]
        End Function
        
        Public Sub resetGame() Implements Jogo.JogoTradutorItaliano.resetGame
            MyBase.Channel.resetGame
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getPlacarIndividual(ByVal request As Jogo.getPlacarIndividualRequest) As Jogo.getPlacarIndividualResponse Implements Jogo.JogoTradutorItaliano.getPlacarIndividual
            Return MyBase.Channel.getPlacarIndividual(request)
        End Function
        
        Public Function getPlacarIndividual(ByVal arg0 As Integer) As String
            Dim inValue As Jogo.getPlacarIndividualRequest = New Jogo.getPlacarIndividualRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.getPlacarIndividualResponse = CType(Me,Jogo.JogoTradutorItaliano).getPlacarIndividual(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_setNewDesafioItaliano(ByVal request As Jogo.setNewDesafioItalianoRequest) As Jogo.setNewDesafioItalianoResponse Implements Jogo.JogoTradutorItaliano.setNewDesafioItaliano
            Return MyBase.Channel.setNewDesafioItaliano(request)
        End Function
        
        Public Sub setNewDesafioItaliano(ByVal arg0 As Integer)
            Dim inValue As Jogo.setNewDesafioItalianoRequest = New Jogo.setNewDesafioItalianoRequest()
            inValue.arg0 = arg0
            Dim retVal As Jogo.setNewDesafioItalianoResponse = CType(Me,Jogo.JogoTradutorItaliano).setNewDesafioItaliano(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getDesafioItaliano(ByVal request As Jogo.getDesafioItalianoRequest) As Jogo.getDesafioItalianoResponse Implements Jogo.JogoTradutorItaliano.getDesafioItaliano
            Return MyBase.Channel.getDesafioItaliano(request)
        End Function
        
        Public Function getDesafioItaliano() As String
            Dim inValue As Jogo.getDesafioItalianoRequest = New Jogo.getDesafioItalianoRequest()
            Dim retVal As Jogo.getDesafioItalianoResponse = CType(Me,Jogo.JogoTradutorItaliano).getDesafioItaliano(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Jogo_JogoTradutorItaliano_getJogadorVendedor(ByVal request As Jogo.getJogadorVendedorRequest) As Jogo.getJogadorVendedorResponse Implements Jogo.JogoTradutorItaliano.getJogadorVendedor
            Return MyBase.Channel.getJogadorVendedor(request)
        End Function
        
        Public Function getJogadorVendedor() As String
            Dim inValue As Jogo.getJogadorVendedorRequest = New Jogo.getJogadorVendedorRequest()
            Dim retVal As Jogo.getJogadorVendedorResponse = CType(Me,Jogo.JogoTradutorItaliano).getJogadorVendedor(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
